### ISSUE TITLE
Drag and drop files not working

### ISSUE THREAD

**Issue by peterlobster** [flathub/org.wezfurlong.wezterm#14]
**Description**
Dragging and dropping files into WezTerm does not seem to work. The files are not copied or opened within WezTerm when dropped.

**Steps to Reproduce**
- Launch WezTerm
- Open a terminal window
- Drag a file from Finder/File Explorer into the WezTerm window

**Expected Result**
The file path should be copied within the terminal when dropped into WezTerm.

**Actual Result**
When dragging and dropping a file into WezTerm, nothing happens. The file path is not copied.

**Environment**
WezTerm version: wezterm 20230712-072601-f4abf8fd (Flatpak)
OS: Fedora 38

**Comment by wez** [comment]
Please use the [wezterm issue tracker](https://github.com/wez/wezterm/issues), thanks!
